### ISSUE TITLE
Class Bindings Incorrectly Adding jscolor to <input>

### ISSUE THREAD

**Issue by evinugur** [EastDesire/jscolor#1]
jscolor will bind to a class that has color in it's className, it should only bind to a string that has a className of only "color" or a string that has color but is properly delimited by a space.

For example:
- `<input class = "colorStopContainer">` matches, but it shouldn't
- `<input class = "colorStopContainer color">` matches, but for the wrong reason

In some projects, people don't have control over their class names, I can submit a pull request with the appropriate fixes if you think this is a good thing to add to the project.

**Comment by EastDesire** [comment]
The issue should be fixed in version 1.4.5.
Sorry for taking so very long, this repo has been dead for months. I just started pushing new versions.
