### ISSUE TITLE
JSColor doens't play nice with some UI frameworks (e.g. - Ionic)

### ISSUE THREAD

**Issue by hanthomas** [EastDesire/jscolor#2]
If the INPUT element is contained inside a DIV that has a position: fixed, JSColor doesn't allow any mouse interaction.  Some frameworks like Ionic use a backdrop for modal dialogs that use fixed position, and prevents JSColor from working properly in the dialog.

**Comment by EastDesire** [comment]
The issue should be fixed in version 1.4.5.
Sorry for not replying to this ticket, jscolor repo has been dead for months.
