### ISSUE TITLE
Can jscolor work with multi intances?

### ISSUE THREAD

**Issue by ghost** [EastDesire/jscolor#20]
I have jscolor within a form that can be dublicated/cloned by the end user. When that happens, jscolor stop working. Please advise. Here is the code i'm using.

**HTML**

	<button type="button" id="button" onlick="duplicate()">Clone</button>
	<input name="color[]" id="duplicater" data-jscolor="" autocomplete="off" autocorrect="off" autocapitalize="off" spellcheck="false">

**JS**

	<script src='jscolor.js'></script>
	<script>
		jscolor.presets.default = {
			format:'rgb', 
			previewPosition:'right', 
			closeButton:true,
		};
	</script>

	<script>
		document.getElementById('button').onclick = duplicate;

		var i = 0;
		var original = document.getElementById('duplicater');

		function duplicate() {
			var clone = original.cloneNode(true); // "deep" clone
			clone.id = "duplicetor" + ++i; // there can only be one element with an ID
			original.parentNode.appendChild(clone);
		}
	</script>

**Comment by EastDesire** [comment]
Hi @oldcastlehq . Add `jscolor.install();` at the end of your `duplicate()` function. This will install jscolor on the new input(s).

**Comment by ghost** [comment]
It works, thank you!
