### ISSUE TITLE
Missing minified version since 2.0.4

### ISSUE THREAD

**Issue by partulaj** [EastDesire/jscolor#22]
Hello, 

The minified version of the library added in 2.0.4 is missing in all recents versions since 2.0.4.

**Comment by EastDesire** [comment]
Hi @partulaj, yes you are right. There were problems with the minified version unfortunately. At the moment, only the raw source is available.

**Comment by partulaj** [comment]
Is there any plan to readd the minified version in the future ?

**Comment by EastDesire** [comment]
It might be added later, because some other developers would welcome it too, but I can't promise when. Some of the planned features are currently of higher priority.

**Comment by EastDesire** [comment]
@partulaj, it is also possible to use minified version generated by CDNJS here: https://cdnjs.com/libraries/jscolor

**Comment by EastDesire** [comment]
@partulaj, minified version is now included in ZIP builds at https://jscolor.com and also in npm packages.
