### ISSUE TITLE
Ideas

### ISSUE THREAD

**Issue by KanjiBoy613** [EastDesire/jscolor#28]
Please make this available on the App Store as an iPad app! Also, add the ability to make wallpapers for each color with the Hex Alpha code, and make the background stay checkered! Make the random color generator and initiating color picker tools Hex Alpha, too!

**Comment by EastDesire** [comment]
Hi @KanjiBoy613 , there surely are many apps for this purpose.
jscolor was never meant to be a standalone app on any platform. It's a webpage component.

**Comment by EastDesire** [comment]
PS: For instance https://apps.apple.com/us/app/color-picker-pixel-color/id1400884755
