### ISSUE TITLE
Suggestions for website

### ISSUE THREAD

**Issue by KanjiBoy613** [EastDesire/jscolor#30]
Please increase the size of the color space to around 200 pixels in height and 200 pixels in width, and make it a gray checkered background for 3/4 of the space, and for the remaining bottom right quadrant, the color should be the same as the text in the text box. This is a suggestion that would make me happy.

**Comment by EastDesire** [comment]
Hi @KanjiBoy613, regarding transparency, the current implementation (opacity slider) seems suitable. It is more compact than having a large area for it. Also, this way it is easier to show/hide the transparency control.
Regarding width and height, I find the current default size 181x101 ideal in many use cases.
If you need to change it, you can use options 'width' and 'height', e.g.

```html
<input data-jscolor="{width: 200, height: 200}">
```
