### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by ldijkman** [EastDesire/jscolor#33]
Thank you!

Used jscolor.js at
to override bgcolor ace  editor

https://plnkr.co/edit/Digj5Fw7D6hxaTU4

![2023-09-05-201645_1920x1080_scrot](https://github.com/EastDesire/jscolor/assets/45427770/5c98ebde-7a70-48f1-93e9-1f520e870836)

**Comment by EastDesire** [comment]
Good stuff Dirk, I'm glad that it works for you.
