### ISSUE TITLE
can not work in the dynamic input tag

### ISSUE THREAD

**Issue by honghh2018** [EastDesire/jscolor#34]
Thanks to develop the great tool,
   I had a dialog to set the color, the dialog would show when use click the button,and then can click the input tag to select the color, 
   but the jscolor can not work in this situation. the dynamic html append Color: <input value="#3399FF80" data-jscolor=""> 
   can not work
   
   how to fix this issue?
best,
hanhuihong

**Comment by EastDesire** [comment]
Hi @honghh2018 , can you please show me the HTML that you're using?

**Comment by honghh2018** [comment]
Thanks for the urgent reply,
   if i using below code into web,  with dynamic script to add the input tag into web, it not work 

   $('.color-div').append(`<p>Color: <input value="#3399FF" data-jscolor="{}"></p>`)
   but if i use css select of input tag like below
   <input value="#3399FF"  class='color-class'>
   new jsColor('.'color-class')  it can work well

Best,
hanhuihong

**Comment by EastDesire** [comment]
I see.

After this code:
```js
$('.color-div').append('<p>Color: <input value="#3399FF" data-jscolor="{}"></p>')
```

try calling this:
```js
jscolor.install();
```

It should install jscolor on the element that you just created.

**Comment by honghh2018** [comment]
Well, The jscolor.install() it good for me, thanks again.
Best

**Comment by EastDesire** [comment]
(-: No problem, Alec.
