### ISSUE TITLE
Move controls to horizontal and parallel with Hue Pad

### ISSUE THREAD

**Issue by linhtv97** [EastDesire/jscolor#36]
![Screenshot 2024-07-24 at 15 44 59](https://github.com/user-attachments/assets/04d8dd94-3556-403c-ab82-bb81c494a709)
Please, how can I move the control down and parallel to the Hue pad?

**Comment by EastDesire** [comment]
Hi,

this is not possible with jscolor unfortunately. You can only switch between HVS / HSV mode, or hide the slider completely, but that's not what you want.

h.
