### ISSUE TITLE
Dynamic content generation

### ISSUE THREAD

**Issue by danielhyuuga** [EastDesire/jscolor#4]
Hi,

On previous jscolor version, there was a function jscolor.bind(); where this function enables the support of dynamically generated content. Is there the similar function like that?

**Comment by EastDesire** [comment]
Hi Daniel,

you can use jscolor.installByClassName('jscolor');

which will bind all INPUT and BUTTON elements with class="jscolor"

Jan

**Comment by danielhyuuga** [comment]
it works. Thank you! :) :+1:
