### ISSUE TITLE
version number

### ISSUE THREAD

**Issue by Mottie** [EastDesire/jscolor#7]
I know the release is tagged with the version number, but would you please include the version number inside the code.

In the zip that is downloaded from http://jscolor.com/, it is included in the non-minified version:

``` js
/**
 * jscolor - JavaScript Color Picker
 *
 * @link    http://jscolor.com
 * @license For open source use: GPLv3
 *          For commercial use: JSColor Commercial License
 * @author  Jan Odvarko
 * @version 2.0.4
 *
 * See usage examples at http://jscolor.com/examples/
 */
```

It would be nice to include the version in the minified file as well :wink: 
Thanks!

**Comment by EastDesire** [comment]
Sorry for not replying to you, @Mottie. Minified version was removed from the repo some time ago.
It can be found on [CDNJS](https://cdnjs.com/libraries/jscolor) , which however doesn't include the initial comment at all.
